#!/bin/bash

protected_branches='master develop'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
push_command=$(ps -ocommand= -p $PPID)

for protected_branch in $protected_branches
do
    if [[ $push_command =~ $protected_branch ]] || [ $protected_branch = $current_branch ]
    then
        read -p "You're about to push to $protected_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
        echo
        if echo $REPLY | grep -E '^[Yy]$' > /dev/null
        then
            exit 0 # push will execute
        fi
        exit 1 # push will not execute
    fi
done

exit 0 # push will execute
