#!/bin/bash

step=5%

if [[ $# -eq 1 ]]; then
	case $1 in
		"up")
			amixer set Master $step+ unmute
			amixer set Speaker unmute;;
		"down")
			amixer set Master $step- unmute
			amixer set Speaker unmute;;
		"toggle")
            amixer -D pulse set Master Playback Switch toggle;;
		*)
			echo "Invalid option";;
	esac
fi

muted=`amixer get Master|tail -n1|sed -E 's/.*\[([a-z]+)\]/\1/'`
volume=`amixer get Master|tail -n1|sed -E 's/.*\[([0-9]+)\%\].*/\1/'`

if [[ $muted == "off" ]]; then
	notify-send "Muted" -t 800 -i notification-audio-volume-muted -h int:value:$volume -h string:x-canonical-private-synchronous:anything
else
	notify-send "Volume" -t 800 -i notification-audio-volume-medium -h int:value:$volume -h string:x-canonical-private-synchronous:anything
fi
